name: flutter_client
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1

  provider: ^4.3.3
  intl: ^0.16.1

  #Firebase

  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  cloud_functions: ^0.9.0
  firebase_messaging:
  google_sign_in: ^4.5.1

  #Other Tools

  image_picker: ^0.6.7+22
  flutter_rating_bar: ^3.2.0+1
  flutter_inner_drawer: ^0.5.7+2
  cached_network_image: ^2.5.0
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/
